openapi: 3.0.0
info:
  description: |
    Swagger doc for SecurityTraderGame
  title: Security Trader
  version: 1.0.0
tags:
  - description: Everything about your Pets
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
    name: pet
  - description: Access to Petstore orders
    name: api
paths:
  /status:
    get:
      responses:
        '200':
          description: ok
      summary: Gets status of server