swagger: "2.0"
info:
  title: "Security Trader API"
  description: ""
consumes:
  - application/json
produces:
  - application/json
definitions:
  WebSocketMessage:
    type: "object"
    required:
      - msgType
      - data
    properties:
      msgType:
        type: string
      data:
        type: object