openapi: "3.0.0"
info:
  title: "Security Trader API"
  description: ""
components:
  schemas:
    WSMessage:
      properties:
        msgType:
          $ref: '#/components/schemas/WSMessageType'
        data:
          type: 'object'
          oneOf:
            - $ref: '#/components/schemas/WSBroadcastMessage'
            - $ref: '#/components/schemas/WSCreateGame'
            - $ref: '#/components/schemas/WSJoinGame'
            - $ref: '#/components/schemas/WSInboxMessage'

    WSBroadcastMessage:
      $ref: '#/components/schemas/models.rest.WSBroadcastMessage'
      type: 'object'

    WSCreateGame:
      $ref: '#/components/schemas/models.rest.WSCreateGame'
      type: 'object'

    WSJoinGame:
      $ref: '#/components/schemas/models.rest.WSJoinGame'
      type: 'object'

    WSInboxMessage:
      $ref: '#/components/schemas/models.rest.WSInboxMessage'
      type: 'object'

    WSPing:
      $ref: '#/components/schemas/models.rest.WSPing'
      type: 'object'

    WSPongMessage:
      $ref: '#/components/schemas/models.rest.WSPongMessage'
      type: 'object'

    WSMessageType:
      type: string
      enum:
        - CreateGame
        - JoinGame
        - BroadcastMessage
        - InboxMessage
        - PingMessage
        - PongMessage