"use strict";
/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * Security Trader API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.RoutesApi = exports.RoutesApiFactory = exports.RoutesApiFp = exports.RoutesApiFetchParamCreator = exports.RequiredError = exports.BaseAPI = exports.COLLECTION_FORMATS = void 0;
var url = require("url");
var portableFetch = require("portable-fetch");
var BASE_PATH = "https://localhost".replace(/\/+$/, "");
/**
 *
 * @export
 */
exports.COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};
/**
 *
 * @export
 * @class BaseAPI
 */
var BaseAPI = /** @class */ (function () {
    function BaseAPI(configuration, basePath, fetch) {
        if (basePath === void 0) { basePath = BASE_PATH; }
        if (fetch === void 0) { fetch = portableFetch; }
        this.basePath = basePath;
        this.fetch = fetch;
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
    return BaseAPI;
}());
exports.BaseAPI = BaseAPI;
;
/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
var RequiredError = /** @class */ (function (_super) {
    __extends(RequiredError, _super);
    function RequiredError(field, msg) {
        var _this = _super.call(this, msg) || this;
        _this.field = field;
        return _this;
    }
    return RequiredError;
}(Error));
exports.RequiredError = RequiredError;
/**
 * RoutesApi - fetch parameter creator
 * @export
 */
var RoutesApiFetchParamCreator = function (configuration) {
    return {
        /**
         * Returns the time and ip address of the server
         * @summary Gets status of server
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        status: function (options) {
            if (options === void 0) { options = {}; }
            var localVarPath = "/api/status";
            var localVarUrlObj = url.parse(localVarPath, true);
            var localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            var localVarHeaderParameter = {};
            var localVarQueryParameter = {};
            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    };
};
exports.RoutesApiFetchParamCreator = RoutesApiFetchParamCreator;
/**
 * RoutesApi - functional programming interface
 * @export
 */
var RoutesApiFp = function (configuration) {
    return {
        /**
         * Returns the time and ip address of the server
         * @summary Gets status of server
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        status: function (options) {
            var localVarFetchArgs = exports.RoutesApiFetchParamCreator(configuration).status(options);
            return function (fetch, basePath) {
                if (fetch === void 0) { fetch = portableFetch; }
                if (basePath === void 0) { basePath = BASE_PATH; }
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then(function (response) {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    }
                    else {
                        throw response;
                    }
                });
            };
        },
    };
};
exports.RoutesApiFp = RoutesApiFp;
/**
 * RoutesApi - factory interface
 * @export
 */
var RoutesApiFactory = function (configuration, fetch, basePath) {
    return {
        /**
         * Returns the time and ip address of the server
         * @summary Gets status of server
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        status: function (options) {
            return exports.RoutesApiFp(configuration).status(options)(fetch, basePath);
        },
    };
};
exports.RoutesApiFactory = RoutesApiFactory;
/**
 * RoutesApi - object-oriented interface
 * @export
 * @class RoutesApi
 * @extends {BaseAPI}
 */
var RoutesApi = /** @class */ (function (_super) {
    __extends(RoutesApi, _super);
    function RoutesApi() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    /**
     * Returns the time and ip address of the server
     * @summary Gets status of server
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RoutesApi
     */
    RoutesApi.prototype.status = function (options) {
        return exports.RoutesApiFp(this.configuration).status(options)(this.fetch, this.basePath);
    };
    return RoutesApi;
}(BaseAPI));
exports.RoutesApi = RoutesApi;
