# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Webapp CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup and run tests with code coverage
      working-directory: ./Webapp/webapp
      run: |
          npm install -g angular
          npm ci
          npm run-script test
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: server-code-coverage-report
        path: ./Webapp/webapp/coverage/webapp
